
deploy_production:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
  - main
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - sed -i "s/SECRET_KEY_VALUE/$SECRET_KEY/" app.yaml
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml dispatch.yaml
