
deploy_production:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
  - main
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --set-env-vars SECRET_KEY=$SECRET_KEY --quiet --project $PROJECT_ID app deploy app.yaml dispatch.yaml
